document.addEventListener('DOMContentLoaded',()=>{
  document.querySelectorAll('.person-card[data-link]').forEach(card=>{const go=()=>window.location.href=card.dataset.link;card.addEventListener('click',go);card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go()}})});
  const reveals=document.querySelectorAll('.reveal');
  if('IntersectionObserver' in window){const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.12});reveals.forEach(el=>io.observe(el))}else reveals.forEach(el=>el.classList.add('visible'));
  const tabs=document.querySelectorAll('.flow-tab');
  const title=document.querySelector('[data-flow-title]'),question=document.querySelector('[data-flow-question]'),body=document.querySelector('[data-flow-body]'),decision=document.querySelector('[data-flow-decision]'),principle=document.querySelector('[data-flow-principle]');
  const data={
    compreender:{title:'01 · Compreender',question:'“O que você precisa resolver ou alcançar?”',body:'O agente começa pelo pedido. Antes de explicar ou executar, identifica a necessidade e o resultado esperado.',decision:'Entender o objetivo antes de escolher a resposta.',principle:'Organizar o pensamento antes de agir.'},
    contextualizar:{title:'02 · Contextualizar',question:'“Em qual situação isso vai acontecer?”',body:'O agente coleta o contexto que realmente muda a solução: prazo, público, atividade, ferramenta, vaga, série, arquivo ou situação concreta.',decision:'Perguntar somente o que é necessário para personalizar a orientação.',principle:'Contextualizar sem sobrecarregar com perguntas.'},
    diagnosticar:{title:'03 · Diagnosticar',question:'“O que você já sabe, tentou ou conseguiu fazer?”',body:'O agente identifica o ponto de partida. Assim consegue reconhecer conhecimentos prévios, dificuldades, tentativas e lacunas.',decision:'Adaptar profundidade, linguagem e próximo passo ao nível apresentado.',principle:'Partir da pessoa real, não de uma suposição.'},
    orientar:{title:'04 · Analisar e orientar',question:'“Quais informações, possibilidades e consequências precisamos considerar?”',body:'As informações são separadas entre fatos, lacunas, interpretações e opções. Depois, o agente organiza um caminho de ação ou aprendizagem.',decision:'Se faltar informação essencial, perguntar. Se houver informação suficiente, orientar sem perguntas desnecessárias.',principle:'Pensar antes de decidir; compreender consequências.'},
    verificar:{title:'05 · Produzir e verificar',question:'“O resultado funciona e você consegue continuar sozinho?”',body:'O agente entrega a solução e verifica resultado, compreensão ou capacidade de repetir o processo. Quando necessário, volta a uma etapa anterior.',decision:'Corrigir, ajustar e indicar o próximo passo até que o resultado seja útil.',principle:'A resposta termina quando existe compreensão, resultado ou autonomia.'}
  };
  const render=k=>{if(!title||!question||!body||!decision)return;const d=data[k];title.textContent=d.title;question.textContent=d.question;body.textContent=d.body;decision.textContent=d.decision;if(principle)principle.textContent=d.principle};
  tabs.forEach(tab=>tab.addEventListener('click',()=>{tabs.forEach(t=>t.classList.remove('active'));tab.classList.add('active');render(tab.dataset.flow)}));
});
